updates to credentials for demo apps
feedhenry-raincatcher/feedhenry-raincatcher.github.io pull request #146
Opened 2017-10-23 16:34 UTC by oraNod

suggested revisions for the section that lists demo credentials for portal and mobile apps

2017-10-24 20:47 UTC, wtrocki commented
I'm not quite sure what was the issue here. 
Can you explain what was the problem?

2017-10-24 21:21 UTC, oraNod commented
I changed a couple of things here:
- removed '.Credentials for the Mobile and Portal Applications' because it seems like it inserts a redundant heading or something. I just think this can reasonably be dropped so the text is more concise.
- put the credentials for the portal app before the credentials for the mobile app. this order follows the order for starting the apps.
- moved the note below the table.
- updated the link text for the json file because it's more specific than 'github repository'
- the text about the sample content is moved to the beginning of the section on running the applications.
- I don't see the reason for pointing to 'xref:building-wfm-process'. IMO this would get the user off topic. whereas the flow for the "Getting Started" section should lead users to the next section for "Learning about Workflows"
- other minor changes for consistent wording

2017-10-25 05:09 UTC, wtrocki commented
> I don't see the reason for pointing to 'xref:building-wfm-process'. IMO this would get the user off topic. whereas the flow for the "Getting Started" section should lead users to the next section for "Learning about Workflows"

It was pointed out that after starting applications users do not know what next. Getting started experience should require minimal time. I think it's worth to have this link to align with our video and have fast getting started experience.

2017-10-25 08:48 UTC, wtrocki requested changes

2017-10-25 08:48 UTC, wtrocki commented on docs/workforce-management-framework/topics/pro-running-the-demo-repositories.adoc
> -NOTE: The Mobile and Portal Applications contain sample Steps, Workflows and Workorders.
IMHO that is useful info. Can we revert that?

2017-10-28 12:06 UTC, oraNod commented
added a new commit to address the changes from review. thanks!

2017-10-28 16:53 UTC, wtrocki approved these changes

2017-10-28 16:53 UTC, merged